site_name: Maleo
theme:
    icon:
        tag:
            s3: material/aws
    palette:
        scheme: slate
    name: material
    custom_dir: overrides
    features:
        - content.code.copy
        - navigation.footer
        - navigation.tracking
        - navigation.expand
        - navigation.indexes
        - search.suggest
        - search.highlight
        - content.tabs.link
markdown_extensions:
    - admonition
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true
extra:
    version:
        provider: mike

plugins:
    - search
    - tags

repo_url: https://github.com/tigorlazuardi/maleo
